import 'package:equatable/equatable.dart';

class ImageLinks extends Equatable {
  final String? smallThumbnail;
  final String? thumbnail;

  const ImageLinks({required this.smallThumbnail,required this.thumbnail});

  factory ImageLinks.fromJson(
    Map<String, dynamic> json,
  ) {
    return ImageLinks(
      smallThumbnail: json['smallThumbnail'] as String?,
      thumbnail: json['thumbnail'] as String?,
    );
  }

  Map<String, dynamic>
  toKindBooksVolumeIdSSrHDwAaqbajEtagJ8fu1x4ylzUSelfLinkHttpsWwwGoogleapisComBooksV1VolumesSSrHDwAaqbajVolumeInfoTitleApiSBerlinDiariesSubtitleMyQuestToUnderstandMyGrandfatherSNaziPastAuthorsGabrielleRobinsonPublisherSimonAndSchusterPublishedDate20250730DescriptionAHauntingPersonalStoryOfBerlinAtTheEndOfTheThirdReichAndAnUnflinchingInvestigationIntoAFamilySNaziPastWhenGabrielleRobinsonFoundHerGrandfatherSBerlinDiariesHiddenBehindBooksInHerMotherSViennaApartmentSheMadeAShockingDiscoveryHerBelovedApiHadBeenANaziTheEntriesRecordHisDailyStruggleToSurviveInABerlinThatWas90DestroyedNearCollapseHimselfApiADoctorTriedToHelpTheWoundedAndDyingInNightmarishMedicalCellarsWithoutCotsWaterOrLightTheDeadWereStackedInTheRubbleOutsideSearchingToUnderstandWhyHerGrandfatherHadJoinedTheNaziPartyRobinsonRetracesHisStepsInTheBerlinOfThe21stCenturySheReflectsOnGermanGuiltPoliticalResponsibilityAndFacingThePastButSheAlsoRemembersApiWhoHadGivenHerALovingHomeInThoseColdAndHungryPostWarYearsThisAMustReadForAnyoneInterestedInTheGermanExperienceDuringWwiiArianaNeumannAuthorOfWhenTimeStoppedScrollUpAndClickBuyNowToReadApiSBerlinDiariesTodayIndustryIdentifiersTypeIsbn13Identifier9781647420048TypeIsbn10Identifier1647420040ReadingModesTextTrueImageTruePageCount359PrintTypeBookCategoriesBiographyAutobiographyMaturityRatingNotMatureAllowAnonLoggingFalseContentVersion110100Preview3PanelizationSummaryContainsEpubBubblesFalseContainsImageBubblesFalseImageLinksSmallThumbnailHttpBooksGoogleComBooksContentIdSSrHDwAaqbajPrintsecFrontcoverImg1Zoom5EdgeCurlSourceGbsApiThumbnailHttpBooksGoogleComBooksContentIdSSrHDwAaqbajPrintsecFrontcoverImg1Zoom1EdgeCurlSourceGbsApiLanguageEnPreviewLinkHttpBooksGoogleComSaBooksIdSSrHDwAaqbajPgPt238DqApiHlCd1SourceGbsApiInfoLinkHttpsPlayGoogleComStoreBooksDetailsIdSSrHDwAaqbajSourceGbsApiCanonicalVolumeLinkHttpsPlayGoogleComStoreBooksDetailsIdSSrHDwAaqbajSaleInfoCountrySaSaleabilityForSaleIsEbookTrueListPriceAmount7759CurrencyCodeSarRetailPriceAmount7759CurrencyCodeSarBuyLinkHttpsPlayGoogleComStoreBooksDetailsIdSSrHDwAaqbajRdidBookSSrHDwAaqbajRdot1SourceGbsApiOffersFinskyOfferType1ListPriceAmountInMicros77590000CurrencyCodeSarRetailPriceAmountInMicros77590000CurrencyCodeSarAccessInfoCountrySaViewabilityPartialEmbeddableTruePublicDomainFalseTextToSpeechPermissionAllowedEpubIsAvailableTrueAcsTokenLinkHttpBooksGoogleComSaBooksDownloadApiSBerlinDiariesSampleEpubAcsmIdSSrHDwAaqbajFormatEpubOutputAcs4FulfillmentTokenDlTypeSampleSourceGbsApiPdfIsAvailableTrueAcsTokenLinkHttpBooksGoogleComSaBooksDownloadApiSBerlinDiariesSamplePdfAcsmIdSSrHDwAaqbajFormatPdfOutputAcs4FulfillmentTokenDlTypeSampleSourceGbsApiWebReaderLinkHttpPlayGoogleComBooksReaderIdSSrHDwAaqbajHlSourceGbsApiAccessViewStatusSampleQuoteSharingAllowedFalseSearchInfoTextSnippetBApiBArrivedInSuderburgOnSaturdayOctober13IInTerrorAtTheGauntAndHaggardStrangerInHisCrumpledAndGrimyClothesMyScreamsHoweverWereDrownedOutByTheJoyOnAllSidesHeHuggedAndKissedUsAllAgainAndNbsp() {
    return {'smallThumbnail': smallThumbnail, 'thumbnail': thumbnail};
  }

  @override
  List<Object?> get props => [smallThumbnail, thumbnail];
}
